### ISSUE TITLE
Fill out the README (Installation, API, Examples) 

### ISSUE THREAD

**Issue by travis-ci-ciena** [ciena-frost/ember-frost-sidebar#1]

**Comment by kuldipsinghrai** [comment]
Just curious, do I need to fill the README here or it will come from my forked repository? 
I thought I make changes to README in my fork and upon pull request we get the change here.

**Comment by vesper2000** [comment]
Yes, when we add a new component, it is a good idea to provide a README.  Take a look at ember-frost-core to match the formatting we currently have.

**Comment by kuldipsinghrai** [comment]
how/where do you create the page that is linked under components section.
