### ISSUE TITLE
Revert back changes made via commit "allow failure beta" when possible.

### ISSUE THREAD

**Issue by kuldipsinghrai** [ciena-frost/ember-frost-sidebar#12]
I am creating this issue to track the changes made to ignore beta failures. Once this issue is resolved: https://github.com/emberjs/ember.js/issues/13888, we should revert these changes back.
file:  .travis.yml 
Simple remove the last line shown here.

```
 allow_failures:
   - env: EMBER_TRY_SCENARIO=ember-canary
   - env: EMBER_TRY_SCENARIO=ember-beta
```

**Comment by rox163** [comment]
Not applicable anymore, post ember 2.12 upgrade changes
