### ISSUE TITLE
Add optional label component prop

### ISSUE THREAD

**Issue by anhuynh** [ciena-frost/ember-frost-sidebar#38]
# FEATURE REQUEST / CODE CHANGE

## Summary
Add a prop for a label component.

## Motivation
* Describe the big picture of your feature to communicate why it should be added.
  * Why are we doing this?
   So that there are additional options to match UX specs when using this component
  * What use cases does it support?
  Additional option for consumers
  * What is the expected outcome?

## Detailed design

An optional label component will be displayed to the left of the button when it is supplied by the consumer.

## How we teach this

* What names and terminology work best for these concepts and why?
`label` prop
* How should this feature be introduced and taught to existing users?
An example will be supplied in the dummy app

## Drawbacks

None since it's optional

**Comment by notmessenger** [comment]
> An optional label component will be displayed to the left of the button when it is supplied by the consumer.

Is this only going to support a component being able to be passed to `label`?  It is a less-limiting design to accept either a string or a component, that way a consumer does not have to create a component just to pass a string value in that is possibly coming from a dynamic source to begin with.

If it is only going to support a component please elaborate on the reason why.
