### ISSUE TITLE
Use ember-frost-core

### ISSUE THREAD

**Issue by vesper2000** [ciena-frost/ember-frost-sidebar#9]

**Comment by rox163** [comment]
just to add more detail - 

1. the style imports need to be changed here https://github.com/ciena-frost/ember-frost-sidebar/blob/master/addon/styles/addon.scss and in the dummy app,
to use this import path https://github.com/ciena-frost/ember-frost-core/blob/master/frost-css.md
2. remove ember-frost-theme from package.json.
